runtime: python
env: flex
# entrypoint: gunicorn -b :$PORT fancy_app:app
# entrypoint: gunicorn -b :$PORT test_app:app
entrypoint: gunicorn -b :$PORT socket_test_app2:app

runtime_config:
  python_version: 3

automatic_scaling:
  max_num_instances: 5